global using League.Builder.Web;
global using League.Builder.Web.Models.League;
global using League.Builder.Web.Models.Player;
global using League.Builder.Web.Models.Team;
global using League.Builder.Web.Services;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using MudBlazor.Services;
global using Refit;
